PRAGMA encoding = "UTF-8"; 
PRAGMA synchronous = OFF;
PRAGMA journal_mode = MEMORY;

CREATE TABLE IF NOT EXISTS Country (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ON CONFLICT REPLACE,
    Code TEXT NOT NULL UNIQUE ON CONFLICT REPLACE COLLATE NOCASE,
    Name TEXT NOT NULL COLLATE NOCASE);

CREATE TABLE IF NOT EXISTS Subdivision (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ON CONFLICT REPLACE,
    CountryId INTEGER NOT NULL,
    Code TEXT NOT NULL UNIQUE ON CONFLICT REPLACE COLLATE NOCASE,
    Name TEXT NOT NULL COLLATE NOCASE,
    FOREIGN KEY(CountryId) REFERENCES Country(Id));

CREATE TABLE IF NOT EXISTS PostalCode (
    Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE ON CONFLICT REPLACE,
    PostalCode TEXT NOT NULL COLLATE NOCASE,
    PlaceName TEXT NOT NULL COLLATE NOCASE,
    SubdivisionId INTEGER NOT NULL,
    CountyName TEXT COLLATE NOCASE,
    CountyCode TEXT COLLATE NOCASE,
    CommunityName TEXT COLLATE NOCASE,
    CommunityCode TEXT COLLATE NOCASE,
    UNIQUE(PostalCode, PlaceName) ON CONFLICT REPLACE,
    FOREIGN KEY(SubdivisionId) REFERENCES Subdivision(Id));
